### ISSUE TITLE
Feature request: Support non-standard store paths

### ISSUE THREAD

**Issue by veprbl** [utdemir/nix-tree#17]
The store path is not always "/nix/store". Nix has the default value set via a compilation option:
```nix
nix = prev.nix.override {
  storeDir = "/path/to/nix/store";
  stateDir = "/path/to/nix/var";
};
```
And can be overridden at runtime by setting the `NIX_STORE_DIR` environment variable.

The current value can be learned by running
```
# nix eval --raw '(builtins.storeDir)'
/path/to/nix/store
```

**Comment by utdemir** [comment]
I _think_ I implemented this on https://github.com/utdemir/nix-tree/commit/1ffb426cc50fb66c95b434ce8bc5c5ce588731b3, and I just merged it to `main`. However, I haven't tested it since I do not have a setup with a custom `NIX_STORE_DIR`. Can you test if it works as you expect? Otherwise, if you could provide me a way to easily get a system (docker container/qemu image/ssh access eg.) with a different nix store, I can test it myself too.

**Comment by veprbl** [comment]
@utdemir It works! Thank you!
