### ISSUE TITLE
Nix tree eats a core, even in idle

### ISSUE THREAD

**Issue by piegamesde** [utdemir/nix-tree#22]
I get constant ~10% CPU usage, even though the application is idling in background.

**Comment by utdemir** [comment]
That is interesting, thank you for the issue!

When you first open `nix-tree`, it starts to precalculate a bunch of things in the background; which takes a while (should be less than 10 seconds on realistic dependency graph). I expect high cpu usage (close to 100%) when it's doing that.

However, it was supposed to settle down after a while. I can also observe that approximately 10% of a single CPU stays busy. I'll try to figure out the reason.

**Comment by utdemir** [comment]
It was an easy fix. `nix-tree` has a background thread which ticks periodically and those ticks end up redrawing the screen (this is because the application sometimes has to measure how much time has passed after changing the sort order). This was quite often, I made it 10 times less often and the idle CPU usage dropped significantly.

I won't cut a release just yet because it is a pretty minor fix, but you should be able to test it if you use the current `main` branch.

Thanks again!
