### ISSUE TITLE
Restore flakes support?

### ISSUE THREAD

**Issue by mstone** [utdemir/nix-tree#24]
Utku,

First off, thank you for having built nix-tree; I have found it very valuable in the past for verifying that certain dependencies have been completely updated (or purged).

Second, regarding flakes support: while I know there may have been no way for you to know this, fyi, I had been relying on flakes support in nix-tree and in fact, I had chosen nix-tree from among competing tools in part because it supported flakes — and so you can imagine I was somewhat caught by surprise yesterday when I found that 415a0acb62e15f8fc2c1fc8e4bd9ca2ae4ae0559 had removed this capability.

Anyway, regarding what to do: in the short term, I and any other flakes users who run into this will be fine since we can simply `nix run github:utdemir/nix-tree?rev=e313e84e474d03b29ff63d05ba813994da2f6a1e` and move on with our day — and I completely understand if flakes are too burdensome to support, in which case documenting a workaround like this may be the best move.

Alternatively, though, if you’re open to it: have you given thought to what would it take to bring back flakes support in a way that was comfortable and sustainable for you (and for any other relevant maintainers)?

Thanks in advance for considering,

Michael

**Comment by utdemir** [comment]
Hey Michael, thank you for creating the issue.

> First off, thank you for having built nix-tree; I have found it very valuable in the past for verifying that certain dependencies have been completely updated (or purged).

:heart: 

> I had been relying on flakes support in nix-tree

That's fair, indeed I did not know that people relying on the flakes interface, I was assuming that people were just using the nixpkgs version.

>  if you’re open to it: have you given thought to what would it take to bring back flakes support in a way that was comfortable and sustainable for you (and for any other relevant maintainers)?

Flakes are not _too_ burdensome to support, and I think having a minimal `flake.nix` does not introduce too much of a burden and worth doing since there are people like you who are relying on it.

So I went ahead and re-introduced a `flake.nix` with commit https://github.com/utdemir/nix-tree/commit/7b01789fb6f5f3143b0aea96505904cce12f1dbd. The only issue I have is that the `nixpkgs` pin might be different across `flake.lock` and `nix/sources.json`, but that shouldn't be too much of an issue if I don't forget to update them simultaneously.

Thanks again :).
