### ISSUE TITLE
Add support for flake syntax, like `nixpkgs#hello`

### ISSUE THREAD

**Issue by bew** [utdemir/nix-tree#27]
Hello, first of all: thanks for this tool, it's really nice to get some insight on a derivation :)

It's been some time that I switched completely to flakes, and recently I tried to run:
`nix run unstable#python3.pkgs.ipython`
which downloaded a lot of packages before working.

I wanted to get some insight with nix-tree and intuitively tried to do:
`nix-tree unstable#python3.pkgs.ipython`
:warning: but that didn't work, basically saying that it's not a store path.

Would it be possible to add support for that?

**Comment by utdemir** [comment]
Thanks for the issue!

Yes, you're right that `nix-tree` currently only works on store paths. But it should be easy to make it work with flakes too, and it makes sense to me to support them.

I will try to have a look at this next weekend (unless someone else beats me to it, of course :))

---

Little bit of technical detail, to future me or anyone else who'd like to work on it:

For every parameter, `nix-tree` runs (approximately)

```
nix path-info --recursive --json --extra-experimental-features nix-command <given path>
```

And I just checked, and that command also happily accepts flake inputs. The reason `nix-tree` currently doesn't accept that is simply because it only expects file paths from command line. So making it accept flakes should simply be an exercise of being not as strict when passing command line parameters.

**Comment by utdemir** [comment]
I just added https://github.com/utdemir/nix-tree/commit/057dd6345dafad4094b0da7b0e63d1ac98d0414d to support flake references. It now simply passes the arguments to `nix path-info`, and not tries to interpret them as store paths. 

It still requires the store paths to be present on Nix store, which is also the behaviour of `nix path-info`. 

Let me know if it works for you, or feel free to reopen this issue if it doesn't :).

PS: You can try it on the latest version via:

```
nix run github:utdemir/nix-tree -- --derivation nixpkgs#python3.pkgs.ipython 
```

I'll cut a release after you try this & I fix a few more issues.

Thanks again!

**Comment by bew** [comment]
Thanks a lot, tested it and it works well 👍
