### ISSUE TITLE
how to use nix-tree - nixos / home-manager

### ISSUE THREAD

**Issue by InLaw** [utdemir/nix-tree#4]
nix-tree 
```
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
nix-tree: Received ExitFailure 1 when running
Raw command: nix path-info --recursive --json /nix/store/qs3lsq6ggyii84hpi4k6mkczqw713ipp-user-environment /nix/store/y8kc459plbj2g3s50mbz1nlxcv104zcy-nixos-system-nixosP33-20.03.2652.076c67fdea6
```

**Comment by utdemir** [comment]
Thanks for the issue.

Yes, `nix-tree` requires the `nix-command` features, which can be enabled on NixOS via setting:

```
nix.extraOptions = "experimental-features = nix-command";
```

**Comment by InLaw** [comment]
give a warning

`warning: unknown setting 'experimental-features'`

[lib.optionalString (config.nix.package == pkgs.nixFlakes)      "experimental-features = nix-command ";](https://discourse.nixos.org/t/using-experimental-nix-features-in-nixos-and-when-they-will-land-in-stable/7401/3)

**Comment by utdemir** [comment]
Have you also set: `config.nix.package = pkgs.nixFlakes`?

**Comment by InLaw** [comment]
no, do I have to?

how should I do it properly?

**Comment by utdemir** [comment]
> no, do I have to?

So, `nix-tree` uses the `nix-command` feature, which apparently only comes with a newer Nix version than you have. Which is actually a bit interesting for me, since I expect you to already have it if you have an up-to-date system, since it's released more than a year ago. I'd first try updating your system and see if you're getting a newer version.

> how should I do it properly?

You can manually use the unstable version of Nix and set the experimental features via:

```
nix = {
  extraOptions = "experimental-features = nix-command";
  package = pkgs.nixUnstable;
};
```

I'm closing this issue because it seems like a Nix issue rather than a `nix-tree` one, but feel free to continue the thread if you have any other questions.

**Comment by InLaw** [comment]
I have 20.03 from 202006
- my default channel is nixos (stable) because unstable is too unstable too rely on it as a whole [I guess you know]

https://nixos.org/channels/nixos-20.03
https://github.com/rycee/home-manager/archive/release-20.03.tar.gz

Shouldn't be older than a few month, right?

**Comment by InLaw** [comment]
now it is fine
