### ISSUE TITLE
`warning: Ignoring the client-specified setting 'store', because it is a restricted setting and you are not a trusted user` when opening nix-tree

### ISSUE THREAD

**Issue by Schweber** [utdemir/nix-tree#99]
This might not be a bug of nix-tree but i'm hoping that you might have an idea:

I switched to [lix](https://lix.systems/) which warns the user when a user setting is ignored by the nix daemon (the default nix program doesn't do that). I have no user settings for nix (at least not that i'm aware of, i'm using home-manager) but whenever i open nix-tree, the following is put out:
```
$ nix-tree                                                                                                                                      
warning: Ignoring the client-specified setting 'store', because it is a restricted setting and you are not a trusted user
warning: Ignoring the client-specified setting 'store', because it is a restricted setting and you are not a trusted user
[===================================================================================================================================================] 1814/1814
```
Do you know why this is the case? Does nix-tree try to apply some user settings that are rejected by the nix daemon or is my system setup to blame (i'm using flakes, maybe this is relevant)?

I see this message only when running nix-tree and nix-tree works fine, so this can't be necessary for it to work.

**Comment by utdemir** [comment]
Hmm - that flag is introduced here: https://github.com/utdemir/nix-tree/pull/79/files

It allows passing custom stores to nix-tree using `--store` parameter, and we pass it to Nix as `nix-instantiate ... --option store <store>` and `nix-path-info ... --store <store>`. And apparently when you don't specify the `--store` parameter, we still pass it but with `auto` as the value. 

So turns out you need to be a trusted-user to do that. And since we always pass that parameter Nix doesn't like us when we're not a trusted user.

But, I think we do not need to pass it all the time, only if the user specifically asked Nix to use a custom store. So we should propagate it as an optional value rather than defaulting to `auto`.

Thanks for the issue - I'll try to have a look at some point if @bryango does not beat me to it :).

But until then, I think you can ignore that warning, `nix-tree` would work fine until you actually want to run it against a custom store which you won't be able to do unless you become a trusted user.
